services:
  postgres:
    image: postgres
    container_name: myim-mono-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myimdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
