server:
  port: 8080

application:
  title: myim
  version: @project.version@

spring:
  datasource:
    url: jdbc:h2:mem:myimdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  web:
    resources:
      static-locations: file:frontend/remyim/build
