server:
  port: 8080

application:
  title: myim
  version: @project.version@

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myimdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: file:frontend/remyim/build
